import AppKit
import Carbon
import ApplicationServices

public final class TextPasterService {
    public static let shared = TextPasterService()

    // クリップボード履歴除外用の標準タイプ識別子
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private struct PasteboardBackupItem {
        let types: [NSPasteboard.PasteboardType]
        let dataMap: [NSPasteboard.PasteboardType: Data]
    }

    private init() {}

    /// 指定されたテキストをアクティブなウィンドウのカーソル位置へ自動ペースト
    /// クリップボード履歴ツールへの登録を防止（TransientType, ConcealedType）
    public func paste(text: String, restoreClipboard: Bool = true, completion: (@Sendable () -> Void)? = nil) {
        guard !text.isEmpty else {
            completion?()
            return
        }

        let pasteboard = NSPasteboard.general

        // 1. 元のクリップボード内容をバックアップ
        let backup: [PasteboardBackupItem]? = restoreClipboard ? backupPasteboard(pasteboard) : nil

        // 2. クリップボードをクリアし、履歴残存防止フラグを付与してテキストをセット
        pasteboard.clearContents()

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)

        // 履歴除外・機密データマーカーを設定
        let markerData = Data()
        item.setData(markerData, forType: transientType)
        item.setData(markerData, forType: concealedType)
        item.setData(markerData, forType: autoGeneratedType)

        pasteboard.writeObjects([item])

        // 3. Cmd + V キーストロークをエミュレートしてテキストを挿入
        simulatePasteKeystroke()

        // 4. ペースト完了を見計らい、元のクリップボード内容を復元
        if restoreClipboard, let backup = backup {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) { [weak self] in
                self?.restorePasteboard(pasteboard, from: backup)
                completion?()
            }
        } else {
            completion?()
        }
    }

    /// 現在のクリップボード全アイテムをメモリに退避
    private func backupPasteboard(_ pasteboard: NSPasteboard) -> [PasteboardBackupItem] {
        guard let items = pasteboard.pasteboardItems else { return [] }

        return items.compactMap { item in
            var dataMap: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    dataMap[type] = data
                }
            }
            return PasteboardBackupItem(types: item.types, dataMap: dataMap)
        }
    }

    /// 退避していたクリップボード内容を復元
    private func restorePasteboard(_ pasteboard: NSPasteboard, from backup: [PasteboardBackupItem]) {
        guard !backup.isEmpty else { return }

        pasteboard.clearContents()
        var newItems: [NSPasteboardItem] = []

        for backupItem in backup {
            let item = NSPasteboardItem()
            for (type, data) in backupItem.dataMap {
                item.setData(data, forType: type)
            }
            newItems.append(item)
        }

        pasteboard.writeObjects(newItems)
    }

    /// CGEvent を用いて Cmd+V (キーストローク) を送信
    private func simulatePasteKeystroke() {
        // kVK_ANSI_V = 0x09
        let keyCode: CGKeyCode = 0x09
        let source = CGEventSource(stateID: .hidSystemState)

        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) else {
            return
        }

        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand

        keyDown.post(tap: .cghidEventTap)
        // わずかなディレイを置いて離す
        usleep(10000) // 10ms
        keyUp.post(tap: .cghidEventTap)
    }
}
